A: date
B: sleep_hours
C: sleep_score
D: sleep_deep_hours
E: sleep_rem_hours
F: sleep_awake_minutes
G: sleep_awake_count
H: average_sleep_stress
I: sleep_needed_hours
J: average_spo2_value
K: average_overnight_hrv
L: resting_heart_rate
M: average_stress_level
N: stress_hours
O: weight
P: body_battery
Q: run_vo2max
R: bike_vo2max
S: bike_ftp
T: total_steps
